// app/layout.js
import { Mitr } from "next/font/google";

const mitr = Mitr({
  weight: ['300', '400'],
  subsets: ['latin'],
  display: 'swap',
})

import "./globals.css";
import Link from 'next/link';
import { ProductProvider } from '../context/ProductContext';
// import { ProductsProvider } from '../context/ProductsContext';
import { UserProvider } from '../context/userContext';
import { CartProvider } from '../context/CartContext';
import { AddressProvider } from '../context/AddressContext';
import { DeliveryProvider }from '../context/DeliveryContext';
import Footer from "./components/Footer";
import Header from "./components/Header";
// import ShoppingCart from "./components/(icon)/ShoppingCart";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mitr.className}>
        <UserProvider>
          <ProductProvider>
            <CartProvider>
              {/* <ProductsProvider> */}
              {/* <Link href="/cart"> */}
              {/* <ShoppingCart />  */}
              {/* Assuming ShoppingCart is a component */}
              {/* </Link> */}
              <DeliveryProvider>
                <AddressProvider>
                  <Header />
                  {children}
                  <Footer />
                </AddressProvider>
              </DeliveryProvider>
            </CartProvider>
            {/* </ProductsProvider> */}
          </ProductProvider>
        </UserProvider>
      </body>
    </html>
  );
}
