// app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import { ProductProvider } from '../context/ProductContext';
// import { ProductsProvider } from '../context/ProductsContext';
import { UserProvider } from '../context/userContext';
import { CartProvider } from '../context/CartContext';
// import ShoppingCart from "./components/(icon)/ShoppingCart";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <UserProvider>
      <ProductProvider>
      <CartProvider>
      {/* <ProductsProvider> */}
      {/* <Link href="/cart"> */}
            {/* <ShoppingCart />  */}
            {/* Assuming ShoppingCart is a component */}
          {/* </Link> */}
        {children}
        </CartProvider>
      {/* </ProductsProvider> */}
        </ProductProvider>
        </UserProvider>
      </body>
    </html>
  );
}
